on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v3*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }} # 此次发布标签的名字
          release_name: Release ${{ github.ref }} # 发布的名称
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false # 是否创建为草稿 true:创建为草稿  ,false 直接发布默认false.
          prerelease: false # 是否设置为预发布, ture或false, 默认为false .
